"""Shared default data and constants for the persistence layer."""

DEFAULT_TEAM_DATA = [
    {
        "name": "Alice Schmidt",
        "role": "Developer",
        "employee_type": "Intern",
        "components": "DOKU",
        "start_date": "2020-01-01",
        "planned_exit": "2026-12-31",
        "knowledge_transfer_status": "Not Started",
        "priority": "High",
        "dob": "1994-05-15",
        "team": "CS1",
    },
    {
        "name": "Bob Weber",
        "role": "Tester",
        "employee_type": "Intern",
        "components": "Generell",
        "start_date": "2021-03-15",
        "planned_exit": "2029-06-30",
        "knowledge_transfer_status": "In Progress",
        "priority": "Critical",
        "dob": "1976-08-20",
        "team": "CS2",
    },
    {
        "name": "Charlie Mueller",
        "role": "System Architect",
        "employee_type": "Intern",
        "components": "iBS",
        "start_date": "2019-06-01",
        "planned_exit": "2025-12-30",
        "knowledge_transfer_status": "Completed",
        "priority": "Medium",
        "dob": "1974-03-10",
        "team": "CS3",
    },
    {
        "name": "Diana Fischer",
        "role": "Requirements Engineer",
        "employee_type": "Intern",
        "components": "TMS",
        "start_date": "2022-01-10",
        "planned_exit": "2031-09-15",
        "knowledge_transfer_status": "Not Started",
        "priority": "High",
        "dob": "1969-11-25",
        "team": "CS4",
    },
    {
        "name": "Erik Wagner",
        "role": "Scrum Master",
        "employee_type": "Intern",
        "components": "Kundenprojekte",
        "start_date": "2021-08-20",
        "planned_exit": "2035-11-30",
        "knowledge_transfer_status": "In Progress",
        "priority": "Medium",
        "dob": "1997-02-14",
        "team": "CS5",
    },
    {
        "name": "Markus Becker",
        "role": "Complaint Manager",
        "employee_type": "Lead Cost Employee (LCE)",
        "components": "Generell",
        "start_date": "2023-02-11",
        "planned_exit": "2028-12-15",
        "knowledge_transfer_status": "Not Started",
        "priority": "Medium",
        "dob": "1997-07-30",
        "team": "CS1",
    },
    {
        "name": "Sophie Krause",
        "role": "Developer",
        "employee_type": "Lead Cost Employee (LCE)",
        "components": "ZL",
        "start_date": "2018-08-30",
        "planned_exit": "2027-03-12",
        "knowledge_transfer_status": "Completed",
        "priority": "High",
        "dob": "1985-04-05",
        "team": "CS2",
    },
    {
        "name": "Julia Wagner",
        "role": "Developer",
        "employee_type": "Lead Cost Employee (LCE)",
        "components": "iBS",
        "start_date": "2021-05-18",
        "planned_exit": "2026-08-29",
        "knowledge_transfer_status": "In Progress",
        "priority": "Critical",
        "dob": "1990-09-12",
        "team": "CS3",
    },
    {
        "name": "Lars Richter",
        "role": "Test Automation",
        "employee_type": "Extern",
        "components": "Testing, iBS",
        "start_date": "2019-11-04",
        "planned_exit": "2025-11-04",
        "knowledge_transfer_status": "Not Started",
        "priority": "Medium",
        "dob": "1981-12-18",
        "team": "CS4",
    },
    {
        "name": "Heike Zimmermann",
        "role": "Validierer",
        "employee_type": "Extern",
        "components": "Kundenprojekte",
        "start_date": "2017-03-14",
        "planned_exit": "2026-09-01",
        "knowledge_transfer_status": "Completed",
        "priority": "High",
        "dob": "1973-06-22",
        "team": "CS5",
    },
]

DEFAULT_BUDGET_DATA = {
    "Intern": {"monthly_cost": 1500, "yearly_budget": 18000, "hourly_rate": 75, "weekly_hours": 35},
    "Lead Cost Employee (LCE)": {"monthly_cost": 5000, "yearly_budget": 60000, "hourly_rate": 0, "weekly_hours": 0},
    "Extern": {"monthly_cost": 7000, "yearly_budget": 84000, "hourly_rate": 0, "weekly_hours": 0},
}

DEFAULT_PROJECTS = ["CG", "iUZ", "iBS"]
DEFAULT_PROJECT_COLORS = {
    "CG": "#FF1744",
    "iUZ": "#FFEA00",
    "iBS": "#00E676",
}

PERSISTED_STATE_DEFAULTS = {
    "dark_mode": False,
    "component_map": {},
    "component_requirements": {},
    "component_transfer_times": {},
    "component_products": {},
    "products_data": [],
    "components_data": [],
}

TRANSIENT_STATE_DEFAULTS = {
    "editing_index": None,
    "gantt_start": None,
    "gantt_end": None,
}
